import { app, esc } from './dom.js';
import { getState, setState } from './state.js';
import { migrate, persist } from './storage.js';
import { validateBackup } from './backup.js';

const unitFor = performance => performance?.unit || 'kg';
function download(value, filename) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], {type: 'application/json'})); link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }
function performanceFor(task) { if (task.completed && !Array.isArray(task.completed)) return task.completed; if (Array.isArray(task.completed) && task.completed.length) return task.completed[task.completed.length - 1]; if (Array.isArray(task.done) && task.done.length) return task.done[task.done.length - 1]; return null; }
function setLine(task, index) { if (task.skipped) return '<li>Skipped</li>'; const p = performanceFor(task); if (!p) return '<li>Not completed</li>'; const load = p.weight === undefined ? '' : ` · ${esc(p.weight)} ${esc(unitFor(p))}`; return `<li>Set ${esc(task.set || index + 1)} · ${esc(p.reps)} reps${load}</li>`; }
function workoutMarkup(workout) { const tasks = workout.tasks || workout.queue || []; const groups = new Map(); tasks.forEach((task, index) => { const name = task.performedName || task.name || 'Exercise'; if (!groups.has(name)) groups.set(name, []); groups.get(name).push({task, index}); }); const date = workout.date ? new Date(workout.date).toLocaleDateString() : 'Saved workout'; return `<details class="history-workout"><summary><strong>${esc(workout.name || 'Workout')}</strong><small>${esc(date)}</small></summary><div class="history-body">${workout.note ? `<p class="history-note">${esc(workout.note)}</p>` : ''}${[...groups].map(([name, entries]) => `<section class="history-exercise"><h3>${esc(name)}</h3><ul>${entries.map(({task, index}) => setLine(task, index)).join('')}</ul></section>`).join('')}</div></details>`; }
export function renderHistory() { const state = getState(); app.innerHTML = `<header class="page-header"><p class="eyebrow">History</p><h1>Workouts</h1><p class="lede">Read-only summaries.</p></header><a class="history-link" href="/">Back to Today <span aria-hidden="true">×</span></a><section class="history-list" aria-label="Workout history">${state.history.length ? state.history.map(workoutMarkup).join('') : '<div class="empty-state"><h2>No workouts yet</h2><p>Saved workouts will appear here.</p></div>'}</section><section class="data-card"><h2>Data safety</h2><div class="data-actions"><button id="export" type="button">Export</button><label class="import-button" tabindex="0">Import<input id="import" tabindex="-1" type="file" accept="application/json,.json"></label></div><p id="data-status" class="muted" role="status"></p></section>`; const status = document.querySelector('#data-status'); const exportButton = document.querySelector('#export'); exportButton?.addEventListener('click', () => { download(state, 'maxsnr-backup.json'); if (status) status.textContent = 'Backup downloaded.'; }); const input = document.querySelector('#import'); input?.addEventListener('change', async event => { const file = event.target.files[0]; if (!file) return; try { const imported = validateBackup(JSON.parse(await file.text())); if (!confirm('Replace current app data with this backup?')) return; setState(migrate(imported)); await persist(); location.reload(); } catch (error) { if (status) status.textContent = error.message || 'Invalid backup file.'; } finally { input.value = ''; } }); }
