import { app, bindHoldScroll, bindTitleMarquee, esc, icon, listMarkup, titleMarkup } from './dom.js';
import { getState, setState } from './state.js';
import { migrate, persist } from './storage.js';
import { validateBackup } from './backup.js';

const unitFor = performance => performance?.unit || 'kg';
function download(value, filename) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], {type: 'application/json'})); link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }
function performanceFor(task) { if (task.completed && !Array.isArray(task.completed)) return task.completed; if (Array.isArray(task.completed) && task.completed.length) return task.completed[task.completed.length - 1]; if (Array.isArray(task.done) && task.done.length) return task.done[task.done.length - 1]; return null; }
function setLine(task, index) { if (task.skipped) return '<li>Skipped</li>'; const p = performanceFor(task); if (!p) return '<li>Not completed</li>'; const load = p.weight === undefined ? '' : ` · ${esc(p.weight)} ${esc(unitFor(p))}`; return `<li>Set ${esc(task.set || index + 1)} · ${esc(p.reps)} reps${load}</li>`; }
function workoutDetails(workout) { const tasks = workout.tasks || workout.queue || []; const groups = new Map(); tasks.forEach((task, index) => { const name = task.performedName || task.name || 'Exercise'; if (!groups.has(name)) groups.set(name, []); groups.get(name).push({task, index}); }); return [...groups].map(([name, entries], index) => `<section class="history-exercise">${titleMarkup(name, `history-exercise-title-${index}`, 'h2')}${listMarkup(entries.map(({task, index: taskIndex}) => setLine(task, taskIndex)), 'history-set-list', `${name} sets`)}</section>`).join(''); }
function workoutMarkup(workout, index) { const date = workout.date ? new Date(workout.date).toLocaleDateString() : 'Saved workout'; return `<li><a class="list-link" href="/history/?view=workout&id=${index}"><span><strong>${esc(workout.name || 'Workout')}</strong><small>${esc(date)}</small></span>${icon('chevron', 'Open workout')}</a></li>`; }
function bindDataActions(state) { const status = document.querySelector('#data-status'); document.querySelector('#export')?.addEventListener('click', () => { download(state, 'maxsnr-backup.json'); if (status) status.textContent = 'Backup downloaded.'; }); const input = document.querySelector('#import'); input?.addEventListener('change', async event => { const file = event.target.files[0]; if (!file) return; try { const imported = validateBackup(JSON.parse(await file.text())); if (!confirm('Replace current app data with this backup?')) return; setState(migrate(imported)); await persist(); location.reload(); } catch (error) { if (status) status.textContent = error.message || 'Invalid backup file.'; } finally { input.value = ''; } }); }
const dataRows = () => ['<li><button class="list-link" id="export" type="button"><span>Export</span>' + icon('download', 'Download backup') + '</button></li>', '<li><label class="list-link" for="import"><span>Import</span>' + icon('upload', 'Import backup') + '<input id="import" type="file" accept="application/json,.json"></label></li>', '<li class="status-row"><output id="data-status" role="status" aria-live="polite"></output></li>'];
export function renderHistory() { const state = getState(); const params = new URLSearchParams(location.search); const view = params.get('view'); if (view === 'workouts') return renderWorkouts(state); if (view === 'data') return renderData(state); if (view === 'workout') return renderWorkoutDetail(state, Number(params.get('id'))); app.innerHTML = `<section aria-labelledby="history-title">${titleMarkup('History', 'history-title')}${listMarkup([`<li><a class="list-link" href="/history/?view=workouts"><span>Workouts</span>${icon('chevron', 'Open workouts')}</a></li>`, ...dataRows()], 'navigation-list', 'History options')}</section>`; bindDataActions(state); bindHoldScroll(); bindTitleMarquee(); }
function renderWorkouts(state) { const rows = state.history.length ? state.history.map(workoutMarkup) : ['<li class="empty-state">No workouts yet</li>']; app.innerHTML = `<section aria-labelledby="workouts-title">${titleMarkup('Workouts', 'workouts-title')}${listMarkup(rows, 'history-list', 'Logged workouts')}</section>`; bindHoldScroll(); bindTitleMarquee(); }
function renderWorkoutDetail(state, index) { const workout = state.history[index]; if (!workout) return renderWorkouts(state); app.innerHTML = `<section aria-labelledby="workout-title">${titleMarkup(workout.name || 'Workout', 'workout-title')}<div class="history-detail">${workoutDetails(workout)}</div></section>`; bindHoldScroll(); bindTitleMarquee(); }
function renderData(state) { app.innerHTML = `<section aria-labelledby="data-title">${titleMarkup('Data', 'data-title')}${listMarkup(dataRows(), 'navigation-list', 'Data actions')}</section>`; bindDataActions(state); bindHoldScroll(); bindTitleMarquee(); }
