import { DB_NAME, DB_VERSION, STORAGE_KEY, REST_MS } from './constants.js';
import { emptyState, getState, setState } from './state.js';

let dbPromise;
function openDb() { dbPromise ||= new Promise((resolve, reject) => { const r = indexedDB.open(DB_NAME, DB_VERSION); r.onupgradeneeded = () => r.result.createObjectStore('state'); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); return dbPromise; }
function legacyTask(item, set) { return {id: `${item.name}-${set}`, exerciseId: item.id || item.name, originalName: item.name, performedName: item.name, sets: item.sets, set, reps: item.reps, rir: item.rir || '1–2', station: item.station, alternatives: [], restMs: REST_MS, groupId: null, groupType: 'exercise', memberIndex: undefined, groupLabel: undefined, completed: null}; }
export function migrate(raw) { if (!raw?.history) return emptyState(); const next = {...emptyState(), ...raw, version: 2}; if (next.active?.queue && !next.active.tasks) { const old = next.active; next.active = {...old, tasks: [], pos: old.pos || 0, restEndsAt: old.restEnd || null, timerEndsAt: old.timerEnd || null, deferredGroups: [], draft: old.setDraft || {}}; old.queue.forEach(item => { for (let set = 1; set <= item.sets; set++) { const t = legacyTask(item, set); const done = item.done?.[set - 1]; if (done) t.completed = {...done, completedAt: old.date}; next.active.tasks.push(t); } }); delete next.active.queue; delete next.active.restEnd; delete next.active.timerEnd; delete next.active.setDraft; } return next; }
export async function loadState() { let value; try { const db = await openDb(); value = await new Promise((resolve, reject) => { const r = db.transaction('state').objectStore('state').get('app'); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); } catch {} if (value?.history) return setState(migrate(value)); try { const legacy = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null'); if (legacy?.history) return setState(migrate(legacy)); } catch {} return setState(emptyState()); }
export async function persist() { const current = getState(); try { const db = await openDb(); await new Promise((resolve, reject) => { const r = db.transaction('state', 'readwrite').objectStore('state').put(current, 'app'); r.onsuccess = resolve; r.onerror = () => reject(r.error); }); } catch { localStorage.setItem(STORAGE_KEY, JSON.stringify(current)); } }
export const save = () => { persist(); };
