const REST_MS = 90000;
const PLANK_MS = 60000;
const STRETCH_MS = 30000;
const DB_NAME = 'maxsnr-workout';
const DB_VERSION = 1;
const exercise = (id, name, sets, reps, station, alternatives = []) => ({type: 'exercise', id, name, sets, reps, rir: '1–2', station, alternatives});
const superset = (id, label, station, members) => ({type: 'superset', id, label, station, members});
const block = (id, label, station, items) => ({type: 'equipmentBlock', id, label, station, items});
const E = {
  press: exercise('high-incline-machine-press', 'High-Incline Machine Press', 3, '6–10', 'high-incline-machine', ['Incline Dumbbell Press', 'Smith Incline Press']),
  neutralPulldown: exercise('neutral-grip-pulldown', 'Neutral-Grip Pulldown', 3, '6–10', 'pulldown-station', ['Lat Pulldown', 'Pull-Up']),
  lateral: exercise('cable-lateral-raise', 'Cable Lateral Raise', 3, '10–20', 'cable-station', ['Machine Lateral Raise', 'Dumbbell Lateral Raise']),
  row: exercise('braced-cable-row', 'Braced Cable Row', 2, '8–12', 'cable-station', ['Chest-Supported Row', 'Machine Row', 'Seated Cable Row']),
  tricep: exercise('overhead-tricep-extension', 'Overhead Tricep Extension', 2, '8–15', 'cable-station', ['Cable Pushdown']),
  curl: exercise('cable-curl', 'Cable Curl', 2, '8–15', 'cable-station'),
  legPress: exercise('leg-press', 'Leg Press', 3, '6–10', 'leg-press'), legCurl: exercise('leg-curl', 'Leg Curl', 3, '8–12', 'leg-curl'), legExtension: exercise('leg-extension', 'Leg Extension', 2, '10–15', 'leg-extension'), calf: exercise('standing-calf-raise', 'Standing Calf Raise', 3, '8–15', 'calf-raise'), neckFront: exercise('neck-iso-front', 'Neck Iso Front', 2, '10–20', 'neck-setup'), neckBack: exercise('neck-iso-back', 'Neck Iso Back', 2, '10–20', 'neck-setup'),
  inclineDumbbell: exercise('incline-dumbbell-press', 'Incline Dumbbell Press', 3, '6–10', 'dumbbells'), latPulldown: exercise('lat-pulldown', 'Lat Pulldown', 3, '8–12', 'pulldown-station'), pecDeck: exercise('pec-deck', 'Pec Deck', 2, '10–15', 'pec-deck'), reversePec: exercise('reverse-pec-deck', 'Reverse Pec Deck', 3, '10–20', 'reverse-pec-deck'), preacher: exercise('preacher-curl', 'Preacher Curl', 2, '8–15', 'preacher'), fly: exercise('cable-fly', 'Cable Fly', 2, '10–15', 'cable-station'), straightPulldown: exercise('straight-arm-pulldown', 'Straight-Arm Pulldown', 2, '10–15', 'cable-station'), pushdown: exercise('cable-tricep-pushdown', 'Cable Tricep Pushdown', 2, '8–15', 'cable-station'), hammer: exercise('hammer-curl', 'Hammer Curl', 2, '8–15', 'dumbbells'), shrug: exercise('dumbbell-shrug', 'Dumbbell Shrug', 3, '8–15', 'dumbbells'), wrist: exercise('dumbbell-wrist-extension', 'Dumbbell Wrist Extension', 2, '12–20', 'dumbbells')
};
const ROUTINE = {
  Monday: [E.press, E.neutralPulldown, E.lateral, E.row, superset('upper-a-arms', 'Cable arm superset', 'cable-station', [E.tricep, E.curl])],
  Tuesday: [E.legPress, E.legCurl, E.legExtension, E.calf, E.lateral, superset('neck-superset', 'Neck superset', 'neck-setup', [E.neckFront, E.neckBack])],
  Wednesday: null,
  Thursday: [E.inclineDumbbell, E.latPulldown, E.pecDeck, E.row, E.reversePec, E.tricep, E.preacher],
  Friday: [block('cable-block', 'Cable equipment block', 'cable-station', [E.lateral, E.fly, E.straightPulldown, E.pushdown]), E.reversePec, block('dumbbell-block', 'Dumbbell equipment block', 'dumbbells', [E.hammer, E.shrug, E.wrist])],
  Saturday: null, Sunday: null
};
const NAMES = {Monday: 'UPPER A', Tuesday: 'LOWER + AESTHETIC', Thursday: 'UPPER B', Friday: 'AESTHETIC'};
const app = document.querySelector('#app');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]));
const dayNow = () => new Intl.DateTimeFormat('en', {weekday: 'long'}).format(new Date());
const go = path => location.assign(path);
const buzz = pattern => navigator.vibrate?.(pattern);
const emptyState = () => ({version: 2, history: [], active: null});
let S = emptyState();
let dbPromise;
function openDb() { dbPromise ||= new Promise((resolve, reject) => { const r = indexedDB.open(DB_NAME, DB_VERSION); r.onupgradeneeded = () => r.result.createObjectStore('state'); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); return dbPromise; }
function migrate(raw) { if (!raw?.history) return emptyState(); const next = {...emptyState(), ...raw, version: 2}; if (next.active?.queue && !next.active.tasks) { const old = next.active; next.active = {...old, tasks: [], pos: old.pos || 0, restEndsAt: old.restEnd || null, timerEndsAt: old.timerEnd || null, deferredGroups: [], draft: old.setDraft || {}}; old.queue.forEach(item => { for (let set = 1; set <= item.sets; set++) { const t = task({...item, id: `${item.name}-${set}`, alternatives: []}, set, null, 'exercise'); const done = item.done?.[set - 1]; if (done) t.completed = {...done, completedAt: old.date}; next.active.tasks.push(t); } }); delete next.active.queue; delete next.active.restEnd; delete next.active.timerEnd; delete next.active.setDraft; } return next; }
async function readStored() { try { const db = await openDb(); const value = await new Promise((resolve, reject) => { const r = db.transaction('state').objectStore('state').get('app'); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); if (value?.history) return migrate(value); } catch {} try { const legacy = JSON.parse(localStorage.getItem('maxsnr') || 'null'); if (legacy?.history) return migrate(legacy); } catch {} return emptyState(); }
async function persist() { try { const db = await openDb(); await new Promise((resolve, reject) => { const r = db.transaction('state', 'readwrite').objectStore('state').put(S, 'app'); r.onsuccess = resolve; r.onerror = () => reject(r.error); }); } catch { localStorage.setItem('maxsnr', JSON.stringify(S)); } }
const save = () => { persist(); };
function task(item, set, groupId, groupType, memberIndex, groupLabel) { return {id: `${item.id}-${set}-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, exerciseId: item.id, originalName: item.name, performedName: item.name, sets: item.sets, set, reps: item.reps, rir: item.rir, station: item.station, alternatives: item.alternatives, restMs: REST_MS, groupId, groupType, memberIndex, groupLabel, completed: null}; }
function flatten(template) { const tasks = []; for (const item of template) { if (item.type === 'exercise') for (let set = 1; set <= item.sets; set++) tasks.push(task(item, set, null, 'exercise')); if (item.type === 'superset') for (let set = 1; set <= item.members[0].sets; set++) for (const [i, member] of item.members.entries()) tasks.push(task(member, set, item.id, 'superset', i, item.label)); if (item.type === 'equipmentBlock') for (const member of item.items) for (let set = 1; set <= member.sets; set++) tasks.push(task(member, set, item.id, 'equipmentBlock', null, item.label)); } return tasks; }
function start(day = dayNow()) { if (!ROUTINE[day]) return; if (S.active && !confirm('A workout is already in progress.\n\nStart a new workout and discard it?')) return; S.active = {id: Date.now(), date: new Date().toISOString(), day, name: NAMES[day], tasks: flatten(ROUTINE[day]), pos: 0, phase: 'warmup', deferredGroups: [], draft: {}, restEndsAt: null, timerEndsAt: null}; save(); go('/workout/'); }
function activeTask() { return S.active?.tasks[S.active.pos]; }
function totalSets() { return S.active?.tasks.length || 0; }
function completedSets() { return S.active?.tasks.filter(t => t.completed).length || 0; }
function taskGroup(t) { return t?.groupId || t?.exerciseId || t?.id; }
function groupDeferred(t) { return t && S.active.deferredGroups.includes(taskGroup(t)); }
function findNext(from = S.active.pos, includeDeferred = false) { for (let i = from + 1; i < S.active.tasks.length; i++) if (!S.active.tasks[i].completed && (includeDeferred || !groupDeferred(S.active.tasks[i]))) return i; return -1; }
function nextPosition() { const normal = findNext(); return normal >= 0 ? normal : findNext(-1, true); }
function startPlank() { S.active.phase = 'plank'; S.active.timerEndsAt = Date.now() + PLANK_MS; save(); renderWorkout(); }
function skipPlank() { buzz([25, 45, 25]); beginLifting(); }
function beginLifting() { S.active.phase = 'lifting'; S.active.timerEndsAt = null; S.active.draft = {}; save(); renderWorkout(); }
function startRest(pos) { S.active.phase = 'rest'; S.active.restEndsAt = Date.now() + (S.active.tasks[S.active.pos]?.restMs || REST_MS); S.active.nextPos = pos; save(); renderWorkout(); }
function continueRest() { const a = S.active; a.restEndsAt = null; a.pos = a.nextPos ?? nextPosition(); a.nextPos = null; a.draft = {}; save(); if (a.pos < 0) return resolveDeferred(); if (groupDeferred(a.tasks[a.pos])) return resolveDeferred(); a.phase = 'lifting'; save(); renderWorkout(); }
function finishLifts() { S.active.phase = 'stretch'; S.active.timerEndsAt = null; S.active.restEndsAt = null; save(); renderWorkout(); }
function resolveDeferred() { const pos = findNext(-1, true); if (pos < 0) return finishLifts(); S.active.phase = 'lifting'; S.active.pos = pos; S.active.draft = {}; save(); renderWorkout(); }
function completeSet() { const a = S.active, t = activeTask(), d = a.draft || {}, weight = Number(d.weight), reps = Number(d.reps), rir = d.rir ?? '1'; if (!t || !Number.isFinite(weight) || weight < 0 || !Number.isInteger(reps) || reps < 1) { alert('Enter a weight and whole-number reps before completing the set.'); return; } t.completed = {weight, reps, rir, completedAt: new Date().toISOString(), actualName: t.performedName, originalName: t.originalName}; a.draft = {}; buzz([25, 45, 25]); const next = a.pos + 1 < a.tasks.length ? a.pos + 1 : -1, nextTask = next >= 0 ? a.tasks[next] : null; const partner = t.groupType === 'superset' && nextTask?.groupId === t.groupId && nextTask?.set === t.set; save(); if (partner) { a.pos = next; save(); renderWorkout(); return; } const following = nextPosition(); if (following < 0) finishLifts(); else startRest(following); }
function deferCurrent() { const t = activeTask(); if (!t) return; const group = taskGroup(t); if (!S.active.deferredGroups.includes(group)) S.active.deferredGroups.push(group); const next = findNext(); if (next >= 0) { S.active.pos = next; S.active.draft = {}; save(); renderWorkout(); } else resolveDeferred(); }
function clearDeferred() { const t = activeTask(), group = taskGroup(t); S.active.deferredGroups = S.active.deferredGroups.filter(id => id !== group); S.active.phase = 'lifting'; S.active.draft = {}; save(); renderWorkout(); }
function skipDeferred() { const t = activeTask(), group = taskGroup(t); S.active.tasks.filter(x => taskGroup(x) === group && !x.completed).forEach(x => { x.skipped = true; }); S.active.deferredGroups = S.active.deferredGroups.filter(id => id !== group); const next = findNext(S.active.pos, true); if (next >= 0) { S.active.pos = next; save(); renderWorkout(); } else finishLifts(); }
function setTimer(ms) { S.active.phase = 'stretch'; S.active.timerEndsAt = Date.now() + ms; save(); renderWorkout(); }
function completeStretch() { S.active.phase = 'complete'; S.active.completedAt = new Date().toISOString(); save(); renderWorkout(); }
function finishWorkout() { const snapshot = {...S.active, tasks: S.active.tasks.map(t => ({...t, completed: t.completed ? {...t.completed} : null}))}; delete snapshot.draft; delete snapshot.nextPos; delete snapshot.restEndsAt; delete snapshot.timerEndsAt; S.history.unshift(snapshot); S.active = null; save(); go('/'); }
function cancelWorkout() { if (!confirm('Cancel workout?\n\nYour current workout will be discarded.\nPrevious workout history won\'t be affected.')) return; S.active = null; save(); go('/'); }
function timer(el, key, onEnd) { let ended = false; const tick = () => { const left = Math.max(0, (S.active?.[key] || 0) - Date.now()); el.textContent = `${Math.floor(left / 60000)}:${String(Math.ceil(left / 1000) % 60).padStart(2, '0')}`; if (!left && !ended) { ended = true; onEnd(); } }; tick(); const id = setInterval(() => { if (!S.active || S.active.phase === 'complete') clearInterval(id); else tick(); }, 250); }
function lastPerformance(name) { for (const workout of S.history) for (const t of workout.tasks || workout.queue || []) { const actual = t.performedName || t.name; if (actual !== name) continue; if (t.completed && !Array.isArray(t.completed)) return t.completed; if (t.completed?.length) return t.completed[t.completed.length - 1]; if (t.done?.length) return t.done[t.done.length - 1]; } return null; }
function progressionSuggestion(name) { for (const workout of S.history) { const sets = (workout.tasks || []).filter(t => (t.performedName || t.name) === name && t.completed); if (!sets.length) continue; const upper = Number((sets[0].reps || '').split('–')[1] || 0); if (upper && sets.length >= sets[0].sets && sets.every(t => t.completed.reps >= upper && Number(t.completed.rir) <= 2)) return Number((Math.max(...sets.map(t => t.completed.weight)) + 2.5).toFixed(2)); } return null; }
function renderWorkout() {
  if (!S.active) return go('/'); const a = S.active;
  if (a.phase === 'complete') { app.innerHTML = `<div class="workout-stage"><div class="stage-info"><h1>Done</h1><p class="muted">${completedSets()}/${totalSets()}</p></div><div class="thumb-zone"><button class="primary" id="finish">Done</button></div></div>`; document.querySelector('#finish').onclick = finishWorkout; return; }
  if (a.phase === 'warmup') { app.innerHTML = `<div class="workout-stage"><div class="stage-info"><div class="row workout-top"><span>${esc(a.name)}</span><span>0/${totalSets()}</span></div><h1>Warm up</h1></div><div class="thumb-zone"><button class="primary" id="ready">Done</button><button class="cancel" id="cancel">Cancel workout</button></div></div>`; document.querySelector('#ready').onclick = startPlank; document.querySelector('#cancel').onclick = cancelWorkout; return; }
  if (a.phase === 'plank') { const running = a.timerEndsAt > Date.now(); app.innerHTML = `<div class="workout-stage"><div class="stage-info"><div class="row workout-top"><span>${esc(a.name)}</span><span>0/${totalSets()}</span></div><h1>Plank</h1><div class="big-timer" id="timer">1:00</div></div><div class="thumb-zone"><button class="primary" id="skip-plank">Skip</button><button class="cancel" id="cancel">Cancel workout</button></div></div>`; document.querySelector('#skip-plank').onclick = skipPlank; document.querySelector('#cancel').onclick = cancelWorkout; if (running) timer(document.querySelector('#timer'), 'timerEndsAt', () => { buzz([35, 70]); beginLifting(); }); return; }
  if (a.phase === 'stretch') { const running = a.timerEndsAt > Date.now(); app.innerHTML = `<div class="workout-stage"><div class="stage-info"><h1>Stretch</h1><div class="big-timer" id="timer">0:30</div></div><div class="thumb-zone"><button class="primary" id="repeat">${running ? 'Repeat 30 sec' : 'Start 30 sec'}</button><button id="finish-stretch">Finish</button><button class="cancel" id="cancel">Cancel workout</button></div></div>`; document.querySelector('#repeat').onclick = () => setTimer(STRETCH_MS); document.querySelector('#finish-stretch').onclick = completeStretch; document.querySelector('#cancel').onclick = cancelWorkout; if (running) timer(document.querySelector('#timer'), 'timerEndsAt', () => { buzz([35, 70]); renderWorkout(); }); return; }
  const t = activeTask(); if (!t) return finishLifts();
  if (a.phase === 'rest') { const next = a.tasks[a.nextPos], running = a.restEndsAt > Date.now(); app.innerHTML = `<div class="workout-stage"><div class="stage-info"><div class="row workout-top"><span>${esc(a.name)}</span><span>${completedSets()}/${totalSets()}</span></div><div class="big-timer" id="timer">1:30</div><p class="next-up">${esc(next?.performedName || 'Continue')}${next ? ` · ${next.set}/${next.sets}` : ''}</p></div><div class="thumb-zone"><button class="primary" id="continue">${running ? 'Skip' : 'Next'}</button><button class="cancel" id="cancel">Cancel workout</button></div></div>`; document.querySelector('#continue').onclick = continueRest; document.querySelector('#cancel').onclick = cancelWorkout; if (running) timer(document.querySelector('#timer'), 'restEndsAt', () => { buzz([35, 65, 35]); renderWorkout(); }); return; }
  const previous = lastPerformance(t.performedName), suggestion = progressionSuggestion(t.performedName), d = a.draft || {}, next = a.tasks[a.pos + 1], partner = t.groupType === 'superset' && next?.groupId === t.groupId && next?.set === t.set;
  app.innerHTML = `<div class="workout-stage"><div class="stage-info"><div class="row workout-top"><span>${esc(a.name)}</span><span>${completedSets() + 1}/${totalSets()}</span></div><h1>${esc(t.performedName)}</h1><p class="meta">${t.set}/${t.sets} · ${t.reps} · ${t.rir} RIR</p>${previous ? `<p class="previous">Last ${previous.weight} kg × ${previous.reps} · ${previous.rir} RIR</p>` : ''}${suggestion ? `<p class="next-up">Try ${suggestion} kg</p>` : ''}${partner ? `<p class="next-up">${esc(next.performedName)} · ${next.set}/${next.sets}</p>` : ''}</div><form class="thumb-zone" id="set-form"><div class="controls"><label><span class="sr-only">Weight</span><input id="weight" aria-label="Weight" type="number" inputmode="decimal" min="0" step="0.5" value="${esc(d.weight ?? suggestion ?? previous?.weight ?? '')}" required></label><label><span class="sr-only">Reps</span><input id="reps" aria-label="Reps" type="number" inputmode="numeric" min="1" step="1" value="${esc(d.reps ?? '')}" required></label></div><div class="rir" aria-label="Reps in reserve">${[0,1,2,'3+'].map(r => `<button type="button" data-rir="${r}" aria-pressed="${String(d.rir ?? '1') === String(r)}">${r}</button>`).join('')}</div><button class="primary" type="submit">Complete</button>${t.set === 1 ? '<button class="secondary-link" type="button" id="occupied">Occupied</button>' : ''}<button class="cancel" id="cancel" type="button">Cancel workout</button></form></div>`;
  document.querySelector('#set-form').onsubmit = event => { event.preventDefault(); a.draft.weight = document.querySelector('#weight').value; a.draft.reps = document.querySelector('#reps').value; completeSet(); }; document.querySelectorAll('[data-rir]').forEach(b => b.onclick = () => { a.draft.rir = b.dataset.rir; save(); renderWorkout(); }); document.querySelector('#occupied')?.addEventListener('click', deferCurrent); document.querySelector('#cancel').onclick = cancelWorkout;
}
function renderToday() { const day = dayNow(); if (!ROUTINE[day]) { app.innerHTML = `<h1>Rest day</h1>${S.active ? '<a class="button primary" href="/workout/">Resume</a>' : ''}`; return; } app.innerHTML = `<h1>${esc(NAMES[day])}</h1>${S.active ? '<a class="button primary" href="/workout/">Resume</a>' : '<button class="primary" id="start">Start</button>'}`; document.querySelector('#start')?.addEventListener('click', () => start(day)); }
function routineItem(item) { if (item.type === 'exercise') return `<div class="routine-exercise"><span>${esc(item.name)}</span><span>${item.sets} × ${item.reps}</span></div>`; if (item.type === 'superset') return `<div class="routine-group superset">${item.members.map((e, i) => `<div class="routine-exercise"><span>${i ? 'B' : 'A'} · ${esc(e.name)}</span><span>${e.sets} × ${e.reps}</span></div>`).join('')}</div>`; return `<div class="routine-group block">${item.items.map(e => `<div class="routine-exercise"><span>${esc(e.name)}</span><span>${e.sets} × ${e.reps}</span></div>`).join('')}</div>`; }
function renderRoutine() { app.innerHTML = `<h1>Routine</h1>` + Object.entries(ROUTINE).map(([day, items]) => items ? `<section class="routine-day"><div class="row"><div><h2>${day}</h2><p><b>${NAMES[day]}</b> · ${flatten(items).length} sets</p></div><button type="button" data-day="${day}">Start</button></div><div class="routine-list">${items.map(routineItem).join('')}</div></section>` : `<section class="routine-day rest"><div class="row"><h2>${day}</h2><span>Rest</span></div></section>`).join(''); document.querySelectorAll('[data-day]').forEach(b => b.onclick = () => start(b.dataset.day)); }
function renderHistory() { app.innerHTML = `<h1>History</h1><section class="history-data"><div class="data-actions"><button id="export" type="button">Export</button><label class="import-button">Import<input id="import" type="file" accept="application/json"></label></div></section><section class="history-list" aria-label="Workout history">${S.history.length ? S.history.map(w => `<details class="exercise"><summary>${new Date(w.date).toLocaleDateString()} · ${esc(w.name)}</summary>${(w.tasks || w.queue || []).map(t => `<p>${esc(t.performedName || t.name)}: ${t.completed ? `${t.completed.weight}kg × ${t.completed.reps} · RIR ${t.completed.rir}` : t.done?.length ? t.done.map(x => `${x.weight}kg × ${x.reps} · RIR ${x.rir}`).join(', ') : t.skipped ? 'Skipped' : '—'}</p>`).join('')}</details>`).join('') : '<p>No workouts.</p>'}</section>`; document.querySelector('#export').onclick = () => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([JSON.stringify(S, null, 2)], {type: 'application/json'})); link.download = 'maxsnr-backup.json'; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 0); }; document.querySelector('#import').onchange = async event => { try { const imported = JSON.parse(await event.target.files[0].text()); if (!Array.isArray(imported.history)) throw Error(); S = {...emptyState(), ...imported, version: 2}; await persist(); location.reload(); } catch { alert('Invalid backup file.'); } }; }
async function boot() { S = await readStored(); const route = document.body.dataset.route; ({today: renderToday, routine: renderRoutine, history: renderHistory, workout: renderWorkout}[route] || renderToday)(); if ('serviceWorker' in navigator && location.protocol !== 'file:') navigator.serviceWorker.register('/sw.js'); }
boot();
